---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: homepage-secrets
  namespace: homepage
spec:
  encryptedData:
    GLITCHTIP_TOKEN: AgA/EUegBigRDD0cBCry49w81FWhDwR7klsBF6r8v73q/Ne5jD1KjOTgsUsIyjubrSAwg8BD5MXcGkfhaugJspx5qQNhMoqpV7J25dMSdSbB1Qu8g56rGS+EBTtgAQ3mYMK77AKlFXOMe+y4dfN193biv9Wyx5tjZkZEThqGwVSbdi+ku/Cezp8/sOO9YrEULdKrEzF19AcUjaxcb6qh8VHmHlUGDcjjpcRu9wW25W/RpwDNLm+pb1v8yxz/FwHprT/kcASV9LIUVVKMIiZtFXTUvf+J0BtYKcW2IdxWKm1skVqxJO2yHYKVUCTyALwz/4Hbku5QKDO6m9aKmJvh8MXzR8LffV0GskNzGgC+5t9seCv/GBYLvvw6yA2/j4tRsGfE5+zYkeRse88IIjA0SXS9ap/Kr08ehjnaqDgota4NK6inQw7tXjFOokHHiv8bTCjojOCX/qc2fijhikGLRhisfKiFS+lxUMZ8f/8INw5oqXRZX8iHyOqTJoLbfSeMaALd2FtOw+qrzUUZDkSsOHZL/5C6adIItcR/asurvjdTGSMr5elfJH+Yd0ZhuSS4aMhj8+nkzOLcDBax/6wGQNAA4uXMpkh3UdepZ+Se8a2EeaR8ovoz6ExMs/iEsoVNRSDZPBuWeNA/7ze2udeK88VW2v4lqt7LaGbE47t/MrQOd6nytc8ndYn98VWg10c28EtbjDeCnqYKFdGYkTRfFMc/3XIIiit43Ql1FHSDrcJ6Y5rfvEvpc1HW/ORKR5fDAdQKUuD1vvTY1M2AHKlRNajt
  template:
    metadata:
      name: homepage-secrets
      namespace: homepage
