---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: homepage-secrets
  namespace: homepage
spec:
  encryptedData:
    GLITCHTIP_TOKEN: AgBGFb6Vy1wM7FP5jplEc38COrlzcfi3IN5fmfox/qnwG1Hr1ifTDJVpHke26fXDiZl8RHOcO/2LTJFBhQQ7f13M+yUZkOSslqnppKixmmjOp6CZNFYNr7QWGgySINHFNhjwDnx25LQWsAVThiD+8sS6ta8nRG0Rhp/36mQTgpWfu4rSMGmAZRPCodLzyAoynlajj/LVycuaWqV6fR/6eChGDp30RPcdAzWZiLvRN2wOaOR+G91pi5vATLvyjpnwt50Efdb+jJrVczy3XfKoPw+/5rjZ3861QNNmJe4GF7S939bugM8FuNV1JeiKkhm+l577QGCfioebkZmT6vkWbCCyNuKfrwvMIcHR/UFEbs9Mv3bUVP3Nys2tTX7pGRDeYKFaB7CO8ZmTY5v0OvUU9gT3bLY+GCTywAztDhG6pvPoI68f7xMN9fO+JGad5NbGv+rjFrkAd2abgNFMxmMGXvjrICHVlG2lam2PULwnzPWJ75SZAdSZqheNfmEKCNixUyvWd9YiCQah0biHJsHJeM4V4WHHKyoh/BfGcS8KRvY5lko2QynUy7X7tMiVTWh8U3DSRTe8OZIy0+EA5rsD168uVOX4fDzeeswKVDl1HicpTTzl+PuAxFuRzwPJLKsB852zR2QVkO+mdfz6581xYogVqDrSAHiL+mcF9miwvYkF3NsqyrG+YcCP/xWYC95oFwLAMjG3xOhRpBL55ednrWZlCgl7Q9nbhjAaFa2IYA8N+PJ/
  template:
    metadata:
      name: homepage-secrets
      namespace: homepage
