apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vaultwarden
  namespace: vaultwarden
  annotations:
    th3borg.org/apps-healthcheck: "/api/config"
    th3borg.org/apps-category: "infra"
    th3borg.org/apps-tier: "core"
    nginx.org/client-max-body-size: "128m"
    th3borg.org/apps-portal: "true"
    th3borg.org/apps-name: "Vaultwarden"
    th3borg.org/apps-description: "Vaultwarden — the safer, smarter password manager."
spec:
  ingressClassName: nginx
  rules:
    - host: vaultwarden.th3borg.org
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: vaultwarden
                port:
                  number: 80
