---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: vaultwarden-admin-token
  namespace: vaultwarden
spec:
  encryptedData:
    token: AgB9SuBcqcZpLsAdY7EMgsQJrPalVjqQU9WvTJA65FYmgfsS5BeciOrp/DdvaAnrcrd4tb8yAuIrO/KvOcvhjyyT49udAJDg0S/JgEurkI6zpYD979w0ho64F/kWkdsuamInQ6FhsW6iv9yBAB0xz0uYN8+LLcDt1Q/vC2U96nsiilIRCFf7L7ONaR+aMrLTV3bgJa1zgMElVlzdSg2zjtMkBA72drkPWerhwABSvvCn+LodvWwWFzvA5lnTPEQ8US17sZh0rLfPTxyrCh9YUiMtzxYWBWd9dsFod7WsvTEvMZ8dOn25dY1MrxYseifWoAWOorioWMLjg5BbcXCxI7KVC2ybxTIQwYKYAFvdRRNBEHSEFci2+ZXU5lXapiFidIvycXPhkQH9K5zv8OfD84ZoP6BizfAvhWmi7XiJA4FZMh8LgVBKPwDp8+m4aDJ8KEPlfn4XeTKrh5fFBSV2wXzikDPR9x7bH6nUbmhiQW+PnFw2CMmzA+OQn4kKHM2syVG3OWGnqRni/7zUpGa1NyA7kU9AW4fth82r/f9PBrpTnFLRCgCtSQlRPJNCUFKLGyq/7Us7uVJHtkGfFet7HqGq/hFgOxSIq1thGRS4c3gZkh4ZkpHVvBUsf+TdeHeo6tDX8CNkoh9nEBcebhPqjqhhYOhvsdM+aeJhRJ1RlhPifOt466DKO2bfTX3yFQIdUZMssdQv/Qb9t8cIBrzqWQ8HCYoB/zKunWXrLxdc1XLeL+eDJfspn6Z0A96rXQ==
  template:
    metadata:
      name: vaultwarden-admin-token
      namespace: vaultwarden
