---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: vaultwarden-admin-token
  namespace: vaultwarden
spec:
  encryptedData:
    ADMIN_TOKEN: AgAbNMTyXy1L5fN0xZlhyo5TF7YMj0+9WrmuwsS2j+49QEjl08sBYg5wZoMNQgttoYca8e9Te1ZRtPBhh9AK4aB3RkD/sjTzsMMGxqpRT+Dr5jys5ipQAgd9ej2NlqvG3Kuu2lf/pTKfdzzSCnLeCMvDjmaJz+fZM298YeTuzloHKVdy7jtS08gFCS6DMYB8OmNtCmaZaulDiteFxhABLMbo1KXrrUgCN0KAVLZbPbZpmayT64b30esHf71gLEtf+W1ypGbd8dXGyrtfbVyMzbu2UYUvW513xYJX2mtPMBhhP2mBhhf9xKbtTLRDWHM4ya6NZ+pupDo+11541Ueg7q9jwBkvvmeZBxr4Dl9PSp8xGOgX6UZysSQ/iRWBWbBi8iYpJZleG+ddDrO8vWfUzvtDKb/YVtd0Nj7u0NjeCo9gcuqrXcV0rqT/i/ce0HqNWg/gWQgpRyzrCSaaNgnSlFkVyZjnyFtZ+H+5D71/X02tFfmAesrQwsjRgofpRM43q4+76ifkCcA4FT2Cmu5XUa2hcdcB0nk03+ORIGXGIZTjr71f+bD2kq0kDum6IPj2rsbkXmTrHgn1vrJkBjRmGd8/J/dfvB1txeBaRMGbm9AeT1SY6Bb7xdeC1AoIkGgDQmDpq3JGBJyQl7l9pF4CUHt7npADRSAxveGclcqZ+k0DLxV6Ltskqw0Me/L9mjW5JbkwQGEenb/pFW5HJ66Axkivod7VuP4jKEVgKHNGXf5GV0HP00r/+JebEyxeUMY6NLj1/96z2ep17oQ0yVsJ7xtxKq5dMJVHj7thZMLXsQxQpFcn5c4eEH400RREIol51HSNCLn4Fiy4TVBwa4JG8sfUzYEmVQxE
  template:
    metadata:
      name: vaultwarden-admin-token
      namespace: vaultwarden
