---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: vaultwarden-admin-token
  namespace: vaultwarden
spec:
  encryptedData:
    ADMIN_TOKEN: AgBSyI3/Jx0zldiaBRGSpkHtoNG1tayqjqzzWNfCBmNFCMX4JUEjUqTbyFF6CuztQnMOo6OP5QYi40imYZbiucynvr/AT15q0S88JDW2PLTuFgF2sKBI1MsdqH7lN4bya6x80RG1RDOjKfhe8Qs9aUOMTMKXjXcMbZpcK2jzH+LPJvgKl1FDyp37YJDHhw8Fst1QOPv+OYv2XDJ5bwf3wCBSY3hpUo/CHOBsPoJdzP53iYFmtFxbbg6nscRCR279wlVRvUXFSAHVadD8a9qrL4++REhL9Q0k+X09FetoY1Zs1nB88zuydTtCg2sgJiLH5FjwpZ+8kc6xuVylwo8XQBuTwOBprzN9ZP6tkoUazEy1XsF6BK/WGEFRHIS1RbGAN0569xIgxvkfswN03IVwdPAsIejIrbb4/QIfZEliCr3B94c038dlc5Zxqs4vF98jN5c0OlSZ1GeLiVnLC+4yAmVzGsrFCX70oK/lCqXKGka2cSKeLl4LjzNwk0LH4Zk+ZcI4Aeg8s5k/fXCrDAND0pi2ro2jBTfuwt0Ed6U2bQL4O1oSSpGJ+vCCH1clV4Cp9lSlnasX27b1vDBPS1uMI8bPWL9w3MG2CPpMHMNdQFhZ1pEGYG8nFKdnTHf6TCoktbKwiLH7W4lfDhfGWp4fHqUjA/N85LCY57ri+rQ0iQh9KevhlS1AB5E83sGV3+6Vm99kbL6q+8EVwWR1AkYLfb8+l7bdKr4PJW3M8IfclpzSkZIpxlb9G2Fo9EoqgkzlErhl393cCcpSWf7a7kfHxjLoQCYaaKu9/QQikDBxQ+8dNguUL2sOfb/GlJSLNXKimY18Q47jkwqytLDS+3ANqfO47Hd+AX6f
  template:
    metadata:
      name: vaultwarden-admin-token
      namespace: vaultwarden
