---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-credentials
  namespace: kube-system
spec:
  encryptedData:
    CF_TOKEN: AgCXy1fAhSrHqHbMLZ+DMX3Gf4C0oxUeqk+jdtEk1tG5dnVaLgbZ8/tNXyh71cImDttvXgq4e4Rbj5/wqr8TV7Nk6j7uojiXo1XaE1WDb8TniN4NR+J5dfD7KDapFOiB4cLfmgg2PxXL84EkjXCimLsNR9JtIHb+WLt09DUQRWFvYUkPQyMqYt/GaweFBKELY4EvfqjK609yj7zo+KX+6SPtzKGxE1VrDcS0mybfZGLmOkK2OW7CiJmjYxQYY/Zh/fF1cwM0xpK/T8A9Eoy8S76djHLEqsGWCKQUM9H7/Vdo8dQh3XBwoVmKRVUBNaKsNphgs7QV6MKMHKHn0hU7KpvhI0zLw7Fe+KOHcIDsbBV3W5UrzGy0qDcvczEhS9PkFFYhYoAjvqCfMdDj6hss9LS9zoQKQ9fOA7cS1CSh7CBVKoeYQ7yhFcru0ZMISAsVHS1wuwU4TRckJMEDAONRj53WS7XAfjU1Cs/KF7ktu3IA7r8bhzWo+FGGLsAO+nrdsMYaydaczvB48tNul5A+B357rjJev9tJkDxsVWRWMvD/aPMf+a7HZdwnNFqcEn2gFlLInVhuax0p8PBRF4c91WeIvCaKso1DFRE5mQ11RlEr3YgROyMW3yoQr0pP/aZv5zw0zrFpQZL/4UVtlGs3NBFGGO9/MjwEqiMGelrgEruZXRWgg/dV45BfneEG3UrSp/lYeXqGunN7ElGJllb6hqwTPK8zg2jYmUgDh0xTvHjvwAa4Awq+mTPp
    ZONE_ID: AgAg8lk08Ec5aVZ0ockdDE8TCZCmEHq7+lWa/kt5bFsSV8bBVV0P456l8wAP68TS1KDaDQzvFfJts5lwz3frVDkNlU1P61u/TeJ9Jyt+OFG9/2/VLoRfqZ7ueixRqRlq/CcAB0AEzGOMrfdAM4j56j4ab8PWFF4oIalMgvqZt9vSHto3j5/Ngcjxz7kNDuRiO/6XKexV5IYr/T+vWdl1mEWLwqDlfqowS4GSQVXG3VttIzYGVJaOcFp6hoUgLU1efSymiohCb3R+59QCWzyxich1B41y+/t5lYk714jOkHXZKhq4oUtj2BPXL9RfHQFCeQh4oaocdEvWCXox4yl4zepawtYhv8JyFnJj3b/MK/EWh2PjlrA4bSiMBytpZ4ECbfN3ASH0H45wMA+O4fXJsvLAHcpIw/57I0w3dBuLzirFnvh1wmBBZg98VK4NSwCGHTYt29ZGsQxyUlzRKQkeIUvDVQnYL/TSw+EwTNLP5hMyN6STtEYnfHYfpTVvCF6NzraralKHeiM+i6MqHiVPxVuYjtZXvhK+VsuYGmqxo6cDV4aQUFJwGop9t1McYGxgX+4adgfSOoyUJuTMDxTYqbUKvASV9NCPhv916YsE/VKsOmI/Bzrm31QixGz9y/ozbb6Rel/8T4zI9qwjbD16dEV8IpiKusBhPmvsL414YtMOp/OhNK7ROcJP06MPEyyquYbB24dh299d9NEZ6hkAmzsxYlqZOHMtz4twKvvD4fBOkg==
  template:
    metadata:
      name: cloudflare-credentials
      namespace: kube-system
