---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: uptime-kuma-admin-auth
  namespace: monitoring
spec:
  encryptedData:
    password: AgCpV431QMRBsush/sLW0zLTq34n6s0AuFRBZVBBi0DJEul6CTbR7j2xeb1jldS0zy+HAAWUEsADQ1wSgp7ZKqhXsgYo7XioWV8DkaqVZDM3MXKxIHd03y/O0sipottKzdToiwLv1xhLaQQShSh4gSVwzXXNNZxgrkvXodqcXlk9c11KT9V5zCnhxavCKxdDxy/ga2vLmd3EmEGdvG9d1tHCSjSrzesWIO4K5LW39wyt23uIPdF+W7HiEmUpJJR9QJ2vm3rgYwKJa2W3p8T/qYsNlq5GwBXDc/c8whJWZSxQZJJO15gh56+lEZdFZwWAiZwQP583GSGcqGuBC5YH4baFsW+fGf3en3TfyFMZ0q3om+DCeoNHgYRBcrPt5YFpiASjFU9uwRSsbpa1bTB8Bf4mETCPh6qjE1nXQ8EKkb8QrzPzD0cz7mpuw7ZIAAykdR84nFXrzDylBPzor/MwTm02DoMf5niPJ9OSD6zRoAnHAFyxUuJqeSD4DjgnKv7gje47XLXmYxG1LHg+vImfA/tyAJvNXGIGq5E7sd9q03hTnzJ27QhJm0/hufD5J5PTQpSvlv7+y4r2JR6G9AfwnSdIWgl/Yj+vw7OiQiHF4vTWl87C8/M78l5rsXPo2a+HOAmaHO40MQmT32DvdTPrNkCSyZP170tiTe2fRrgBnwA9uuW7owOSfQRWDYDEd+KtqmUAe+OsxgFX1/a4hb25NN0C/slsn7VjPhBUQAc2QENofadZScnYx5sfMY64kw==
    username: AgAlZ6LkT/hxbWsCl5jV59S2ztRk29p7MgVNqTGek5RPadXzI00D4AemOlUXoFN/QGPJlO5Hf4idefeRyggJC805GSlUx+jSFzOFSxpCwDSXe4//8yc7XfyDw1XxKLO4UUJUNvCj/4tq1jBXY4Htf7PNHxNjxFqSPPtWFYOlaeOTYRjaM1XoVBNd2gp9V6YhShNM/riseNK5iXA0+JjiUjguKeV1TbKB+aByNDiEDBejoGUqDRtOHnK3WqQjrLC/Iju9x6Pdhn7TGngwP3FjSXtEiwamLtyHwjtMvjKpA26fbbx0hMGguE8ZbbYuh92oesZW8tZ1dHhLlP7yyVESZKqGemuFOXqtqN1UynU24B0FP2QaC0CwlhlaPU6JzeXxhlS2fQOxIgA1MSr4UTrBOKfLne/wkl353xOCT0QormzUEKHrUQ5Z9nCIsq0xlgxW4YbguMepEvivmtD2K+8mNVTVqe4TNNYli/alq8Oke5T+GYrY1iFvxt8mDKK9I2FCfO7PmOMjYklZzo4hCmXOSlcoSZtvrFrdSx0NFSXWjdfrCdPUbmrKJZJd3Alixorz+APM2bAgCUmvcZfqf/3ZZ7WOHSqXACXpD2sSKdOX+idKRssoz9ukQCWDm4u0tSt5mhtFHctgY8Ij3IrusD+Vm6SvWN5gRCJW3G2EP5Qw2laHhKOF7Zst7XBdgPR3L/nUM8Hh3y23Wc7ZDTz2
  template:
    metadata:
      name: uptime-kuma-admin-auth
      namespace: monitoring
