---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: uptime-kuma-metrics-auth
  namespace: monitoring
spec:
  encryptedData:
    password: AgBTA/Noerpz5oywiarK9rnXLRLqUNjTCQAJvN3fOz4iDUu5XL8wo6zYg6Om9lTNXfo/nxRceMNyQwFlHgpaRgbVchoDoaHiySjP0FZMzaLscGG1uCxcDDVVTzF3dht6PTekCxP3FSv5qkluCGbjAfiqbsJ9wauvVtyURe1cNH8jvZR3KyqhnDaF50xG1e/nCY/ZG7H1FNOpnLOzRGAVy1o08KW13aKEreQWvDO51GXWiverAzwGQhvztcT+WUrucraBYCAmoIgWD+tOMwndtIPeVAl46gAO2nfaGo/E7vWdxdkCkgO3/fy3KqNOBJG3IXv/65pJsp+MpPoeKgi8TToZYRyH+4oKDuwBNEF1KAGIrZxMcdhxxHYudryriHYf/1PEyjD6TG/4lhHqtZbszxJqoysFyHd1zZHMCeW/SXEpikFI2dFPB+QFSN1Rgi8CIO8NWhU590C0p9PKI1nEDUmw0YyOdblImjrt60kkDAMALM9eMA/2xJJ35kzNbfcvr9Utb1D829h1aZFS6FjzdHJIYkDWuSDZoo7RB3usvOXu96YARa7RmcX2rJh/gSChhS1LlhsXY86pADw34I01jqsy2JFGHDYC1nIa5EqJqw2wNLDXx/txTUTNPU6VkhTGORVxGpZ/SaHWe6m24dL46iSRP6T33Ij2+M+nzTTUoMFCkzYocnCNjiCbz/6ji2CVuA8Dk0vi3W/pZAfyxNSFOoP7v2nfB9+bdNeMdXeJg0eh3evWdPxigQ9gwdM9NA==
    username: AgCTA5HUaHgP7xb09MB5scXxuaGcZwnBDqxpnVeEJkjeUuKrblzLvrj5J5+C5aQtxZ7wV1Ee9kNbiGgwYR+2NOvbqxgXdOgaECLGPqiyhm4clnoc4O2yNoDqfsYgoU6sRzNjONvte+mPZRBRiVppu/OhmByiiGAukL8HxnsRpB/3KEMEqtLTHc6d6Za1dJzW0V3kValmZoRBT8dNHYiCmCXcuskh9SPjvtP8zAHGSCNZmLqe4rrhquUHulvBmIEdVcScMmTBdDnzmFtXe0KSLX8ODWJHN51Lxy11iBvLXatrCQEQGezojUzdGQUdwi4MQcs2ceh5Q0yqmRDFkGRZx1HU0cYrnFAUTck3cf6ig7gCcV+4Qefd84KNSVaqO0AB1PSNSkopitA8Rqk3Va0DmE0Ip0ykGC6ksLRkchd3/V8/Qv5n7U4ikHnJhK/iGS05yK2EDfLiSkyJjy8kNWyfxXWMYTH0CIvMwGRgX6ki/YB79qWSmlKXBY237aDY2bvVBIHjlNQaDQeQRmnA5Cf9VRvUeYgf4LYEfk4L4MaLC5RTA+lI85+6LLdUTQdbeAmKBa1iGgaaFisXWLG6VX8UdG7WZfMMs5u6a47Rl9o3bB5Q4SuTUYRLdk47ODDgyBIaqXpB6M1CkuNqknDptBi2QMVLXoI8B/w0FDROV/WalqzG08opd74ib1oWErO01XXvqfKgB5Q0pfZJ
  template:
    metadata:
      name: uptime-kuma-metrics-auth
      namespace: monitoring
