apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: authelia-ingress
  namespace: authelia
  annotations:
    th3borg.org/apps-healthcheck: "/healthz/live"
    th3borg.org/apps-category: "infra"
    th3borg.org/apps-tier: "core"
    nginx.org/proxy-read-timeout: "360"
    nginx.org/proxy-send-timeout: "360"
    nginx.org/location-snippets: |
      proxy_set_header X-Forwarded-Proto https;
spec:
  ingressClassName: nginx
  rules:
    - host: authelia.th3borg.org
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: authelia
                port:
                  number: 9091
