apiVersion: apps/v1
kind: Deployment
metadata:
  name: authelia
  namespace: authelia
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authelia
  template:
    metadata:
      labels:
        app: authelia
    spec:
      nodeSelector:
        kubernetes.io/hostname: borgling-1
      tolerations:
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
          effect: NoSchedule
      enableServiceLinks: false
      containers:
        - name: authelia
          image: authelia/authelia:latest
          ports:
            - containerPort: 9091
          env:
            - name: AUTHELIA_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: authelia-secrets
                  key: JWT_SECRET
            - name: AUTHELIA_SESSION_SECRET
              valueFrom:
                secretKeyRef:
                  name: authelia-secrets
                  key: SESSION_SECRET
            - name: AUTHELIA_STORAGE_ENCRYPTION_KEY
              valueFrom:
                secretKeyRef:
                  name: authelia-secrets
                  key: STORAGE_ENCRYPTION_KEY
            - name: AUTHELIA_STORAGE_POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: authelia-secrets
                  key: POSTGRES_PASSWORD
            - name: AUTHELIA_AUTHENTICATION_BACKEND_LDAP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: authelia-secrets
                  key: LLDAP_PASSWORD
          volumeMounts:
            - name: config
              mountPath: /config
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi
      volumes:
        - name: config
          configMap:
            name: authelia-config
