apiVersion: v1
kind: ConfigMap
metadata:
  name: mcpo-config
  namespace: ollama-webui
data:
  config.json: |
    {
      "mcpServers": {
        "fetch": {
          "command": "uvx",
          "args": ["mcp-server-fetch"]
        },
        "time": {
          "command": "uvx",
          "args": ["mcp-server-time", "--local-timezone=America/Los_Angeles"]
        }
      }
    }
