---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: lldap-secrets
  namespace: lldap
spec:
  encryptedData:
    ADMIN_PASSWORD: AgCthlaE4HBKG1kSikAwBgbc8+C2nBTJV3MvQb43aLD4536imbizwrnYfvPtJYG/QXIGWK54T1lB5QtgHBLyS6I9dDaGenFlRj+jx4EFCWdzHSqShTUnT8hFME2neKBs7xME4vhZr03OLyYJ7IkTTkiOgsFSqs62Z55HAoBhKDVGBsmz6dX2WP8GW7s/SqYFeUcsZe4MV6pAaNkmukvreELbSq6WE+hz28e/WzmYxOMzEI3pgxYd1qrqhzP6K+0etcNOyuboLfrD1D7bDyU2JWy9LxZcyzf61/noHvA4XgDYOg69XNiy5YS1UhfE3x2LBqpD0bM/WVgUnPTmTUpS2acFUnv77m6yNE3l637d0aLMY74zfHv/fB5L3w2E3+0pz7IEKz3Bpr/l/XH2SKrp4FTOplG0IiABzGgCmjazFRKRWR/G4LvU0ddKRryjHvGisV8MBLkneEw0KAGDyuHFiNMqlmTf8nIwD/Tkt+0f2l1dTJlymkHZ9uTuOPCT/9kpCQV20U0q2HAKaK6FnV4PCH1aNqPewy6dBVErNHNV12rzgqFNJd79tyUzBHAzOT8tMVKaey7UctWG8zFJy+D5ikLkiNiZeV0u5OIW2fXkOlsdyX6+He557IvUTEpWRHOGPEe8BoueTtdM4ytRGuGh2cy4Xigd4kwF8Zc8rJunzAkg9aCumZGdSGRgsfzpONb3ITUC1EYKZds45XsqqCsv5yVcgzvBxMETxv6P3Td+E87zI7mzIw2CqK/aWeWg2A==
    JWT_SECRET: AgBAiiMv7ok36nH4OkWPFmdTWjy1eB2r08feWTREqTbA9qc8AdnrzuYAHdEac+EKpqHwyiKb4kYA01nDsJzzLkYmAfwrc3rbLrkSAQj/uxJLqZOP6Y9XCnLNZnRtwMWdIfrOTmHbvq57pQxhxxHIx3HsM3LsgZGP7eENDaeueWSIL+AUoO/bxImuwxag153OOyTCUt1F/N4SvujRdwbc5qaHsWbSEoyNiiqcdqwtIksxOqEOIORbSN4PbGI/sk4q94lsQZMDhx+TGudTrji4KVNki9ABapp7lGKOhBSvE9bo38Tvq2hLctfJ9TtVeKs4Nso2HHc9KruXJSPY/xuvD1b/E/mDYAudwNpRZ0hRTwbfRR8De6woDUiGRYGtVNH4HURG41Yv7qjrHVuBO/YrF6djXWzK1EDO8U1/1C7iUljo1DFdL7MhPzPUyv6ZznOhgOqrXhZYq5pg65VVGomOMcL47hEr3lnDSLiDKWtWXkaabdQEIizEsWapoR3fVovfTjxDFsYPvHSN6y16qMix3o+AyvAmmfuRYLHVlVPr+psSJUfVEoNCbZK+a/BjpSd252MW6AjDtpWgnw0nIuB35oPNGmjFGdwbyhPF+YCtSl7edrny0Oorp8Q8Dm6NuWzP7ewXhUOZGzSBjFAvMwl+GdESDCuRo9YDMRj3ftbhfcaMzdQvajugFr0bBfepN+V73BexobR4j3JV/Wh87Ermd+4ctHKQJWecjY5yQsyQaW7GClFSPbuXvKoBmF2rsQ==
  template:
    metadata:
      name: lldap-secrets
      namespace: lldap
