apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookstack
  namespace: bookstack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bookstack
  template:
    metadata:
      labels:
        app: bookstack
    spec:
      containers:
      - env:
        - name: PUID
          value: '1000'
        - name: PGID
          value: '1000'
        - name: APP_URL
          value: https://borgling-1.tail20def8.ts.net:8443/bookstack
        - name: APP_KEY
          valueFrom:
            secretKeyRef:
              key: key
              name: bookstack-app-key
        - name: DB_HOST
          value: bookstack-mysql
        - name: DB_PORT
          value: '3306'
        - name: DB_USERNAME
          value: bookstack
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: bookstack-db-secret
        - name: DB_DATABASE
        - name: SENTRY_LARAVEL_DSN
          valueFrom:
            secretKeyRef:
              name: glitchtip-dsn
              key: GLITCHTIP_DSN
          value: bookstack
        image: lscr.io/linuxserver/bookstack:latest
        name: bookstack
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 256Mi
        volumeMounts:
        - mountPath: /config
          name: data
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: bookstack-data
