apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bookstack-mysql-data
  namespace: bookstack
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 5Gi
