---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: bookstack-db-secret
  namespace: bookstack
spec:
  encryptedData:
    password: AgCVwlORTs2P9R+tK9KJhibtuXLdoaNiQAf7VBdfDE5LBOxadUQQkdf337wWSB/aQ8ru7y3qzn2wkdDBFBAaYWDH4KXtkTP3+p9D5JOAJL4JvJ9CszTWkC0rKHbyhbc6+iAz+pBUiILwTM+7CMeY7kGYckxRKIW/TYzm6kpfbRf9XveCG/JwH2/ymTMRQ55rtKP3Ygrr7tmptM5S8VXT+ZZM3VMAFeh92TVdffGe0X5Oo1DvkRGwHlgUV3TFaKm6ZweLaxs9FQp1NBwm8ZNVad/95xseKfPpwCi/yoTg0NmJLlm6ZhCPxfb3P3SXKP11N7YZmtbezDpV6UQvU5QRRRZVqRFkHLcAMM1A+LBtnqNUZzS1F0oLTQjocUPy+l9wvrH0t6fGYiz58QWdBNr98JR8YCJC9zswKDS8kz16A+8D3RXzg+akz7rYlXq+KtxYUR7PY7GFAvo7dzptOMB3gkcr/xRxHmw5DzdRyw3sfVdAeEe3bTYlimP6/cpEnv1D998FUHYZxFgaUMzu4+HKuLK6ThQLWGPC0Sers2Q4tGr8R9WWu9jCSk+nVumfmUFSy+488/SOJkhYTAxZvtmENg67V7asGS/ZG9G85k3498Ch0kXi5MVw4JMeaEpPxQoWrQCd/L8gXv8N/qIu1ProzeJRFtZWBqgiNExh43xyJiqbbO0s4ROyfhZKKhQ0yl8U3GYQ64fKgXFIo0o=
  template:
    metadata:
      name: bookstack-db-secret
      namespace: bookstack
