---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: bookstack-db-secret
  namespace: bookstack
spec:
  encryptedData:
    password: AgCg3xWtuSHu/P2CHh5X6AThJ67BDbZ7NYTnKUztVNp5ONr1VrivtVb4l5NpbOLxPTZ3+Pv3Jii8p580MH4i/AWAT8a5ggP2zgTlBi71KVSc1IQ6ttvxjuyNghARrzMYYse/ELccaqbeC6yYgRsWCyDNWhBlipgN8z7++noV26CmdOfEWwnPWagva9LwZG510JuEmt+c+gNfsIRpt0rlXjQBpl8dhcXQYFGJd5Rs/aVNWcj9TUKtizWXJMIcBkgoqOuBAmLOS1xMJA1KC8RqAQCchHlrTwZEX0uOO92neSCnWIARlrqCMXuhSkmSbV92fcPh4rD6GyN5GdeHK1+oyoh0Hun2/GOZxJHxTXgG1jmbMClw/Q+f2FQ+kUy/4w6uOcAgOlTzFVyptrsh2g0D60kBO0UMdRyrJQMmb3GGgLDjW01kIOgdVYYH1xVGnVWXmqvnakXseyTa8UNTKxsWlOoP22/Y0GOCimP96wvvNlqoq4p8AD29/z2QVN7uRHDgGOIs6nq364CIlPGKN0KmfNlkDuY7AZx42aBeVC+3GM6mKlCm/YDgET5uQpcXW6zeVH3eoMHV1j4HNd0EvU8cJjGpZtzYd7I7xv+FPIR5c5rI48zz5CME5QSbaKpvEnCLcpbiO/gv9qqPlCTQ+sk5v0ocuMw+WP8dF8jr+KauUtzlKF2XUeKqtXofZdpMY7aVsHofrlPovXi0EgBEKszl8kA2IgguR48aLn/jMwDPknjOXpVL+ow4rDuKL+Sbeg==
  template:
    metadata:
      name: bookstack-db-secret
      namespace: bookstack
