---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: bookstack-db-secret
  namespace: bookstack
spec:
  encryptedData:
    password: AgAj5VdWD8X5FmKeuc8Ljo+umsNDB/HCqh2TJiYUz3TQYPi/81xLHwe6DV9leO0WG3vU395Jk9UfaGAw94FwaUiQ5ar8zpHlvfjEeGLiRShXoHRc9H+nO6lRAx7YfFiwkuhjSluW/rLNz8aXkZpOAU+oOH3jiyLNoqbKlFkvCFk5Pd0oj4qaARrZIjPX/wqARd6gYLDy065fnRyZR1b3UU3NgXfGAA2/x5nHPIcgNGn6H072JPard38rRNRhdybUi03sLu9PzY5LDNcbCwRsC/fFGzpr9UhayJZN5lyiWgMe6hSg2q1u0YiHw6aUINzs41GVnD5/ilZ84oCZ6db4NuXhZwbRn+IBJAattRcF81k/VhYTUgpnDRGfJGd5cj5YbWQZclcMQ0rskD3kBMkg6epzri4lbqyKlaaDd9ZvHD+WyXGF0UehxVqtC2k2Cm2X4Uk4yohUwlRbOW7s/dO8MbGRAtceIyPXdm2lz1F9u9SwiSZ2ISt1z1ZKu/7z2miIA9mgUQNHLAIqjB9GQzUPX96Wk6xYoM6Mpif4k/E0XEwkQiMxu565ek2OVlDY0Ena7X+X/tLa/CnBMnyj7Rh6oP+qyRQW5hUNyc/gKXNC1n8Uwe+lodIjDcwRx9w5WUMMyNKM52IfNRQH+wWmcos8VBZGNs2mfLz6fj4rDjuPgJoTl9rSRM82MGZ+NMnRrFAe4K3zHRrRaCnEz7GnU1i39yehnAOCk4D0pn0Ex20Xph3GOv17hF3q9IXbA73orQ==
  template:
    metadata:
      name: bookstack-db-secret
      namespace: bookstack
