---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: livesync-couchdb-secret
  namespace: livesync
spec:
  encryptedData:
    password: AgCd8vXDxW+O53qr27PwUuZI2T9mUxEmjqDX+Zjb5XSdQgz5d5XljvlohG4wUEbWAkidcyEeZwiLdO0MvW+am3GEvKsJ4NAkasR/qGaP96uKfAd5bx2wSK23smnm7K47GJMoX//dmBeGIjv38ZW3P2jTcwLRpM7mms2OWO0x2X7K52/nwurqQ74gpzGU4nDznI/PciNpKGHGcmcLVV49LcAftXgyEkPsFWPJEIqYjbT84cdGrjWuKkhe+fv+atOlSUwiXin2+cC7pq7GBxwiYQxTesqMQRh2+PK+F55WvsByZ60unuX9oTcvrKuFiKb1GGkxQ7ug8WoHl/DDjXZVAXDTYez0VeBXkH+FHjhKU5nkuB4icDV3uYH3orlLowd1QTt0l+O5fxmO/ECmw04IPgom8+UXaP4e8a50hrNv9B+5+OOG5ZvkEzQ007f50uVvCdnr1NYKadhtk0TrgyDZf54Uvd3xXlQGDpJgSQhpOcLsz668/yvtXsnhyaG/UBAfBzjsiLD69gCwxoWbladVhzQYxBleiGGrCvVbIfGjAAAx2qAhJtYxSEGh6PgqkNBxRE3QTwZPEE7Zd9PjBQ2YaDuEEQvq+1DH3KZEi1Ia0WPeD1UePFiTG1jzuR1tn/L8SlkpW85NQzZB7lhvvB3FK/zTMKwsaaIK5I+PshcjIBC9q+V9Ng16QEtkl4Vw1LpJOZ13OhXk0UB2+JuqCo41LvGTuKk/CUmQdpFx0sVSLl2M5nLD3DPr6OXtSjaYkTeI14OICycvAjKE1g==
  template:
    metadata:
      name: livesync-couchdb-secret
      namespace: livesync
