---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: livesync-couchdb-secret
  namespace: livesync
spec:
  encryptedData:
    password: AgB1Fq8vxQfakOJzFYMJJBSwDLwH05D1cOe73UiiZwVJlxO55oFpO18oz38fpQ5nPVdw7Ou1E+W8vJBtupUGQX85RIoZhNNU7suSH+v/UnF21ZxYQvYP5uONIv9CMqjDwSjq0gAo4WwMrh1VgbmQQt7Y4G0vHZ/CWpVCKAtKQLAhgvM26v3MX76QNQ2HI3NhhxYwPSo2lTsGodFHTqjFSigNxTapZ4Y4xdcczPWJQXERI92pxUi4tT2wBzY5AM/LI9lEOKGipN6ACiH3WTbimutDuF5xUHudtmFjbQWdykvPdumEbatzBp+OSV/BXloZPFl6StxYeaKMAKvzu5u3Q22FZ0XacdmCBK9shyeXOY2Xa+++RbMXHcXutk+diNKDdpaX3A1c/PPSAflg9kXckqX9lZHV01cp95NE7qT5dtSWphknP4SWAlUzeGEdrwFaPdZj5495sAJqAPLw6QzVFnjSjofAU7V8bKHi5HtSpoxXg3Ml9IgYs+ntKCWcUZSBfdU5fUHTHXdytPTLza8At2Ix9HnSps7W2V5WBS9rq14v+22+VLX6CGR3MJCDKXFudf5m491ENw4hn7Y/jfr00j/y+nZO9z7ox1FwVZ5L1sstR+/ayrlQzoxmsQemBfli2UYrphJtS3K0BfHeIBkwlAvRvQuWG8LHDZ5zvSRDHpfpvae1ANndGlIupFD8M2NxmI2KrzI+X509MOEEmCwWjQtPwqqJTvT0cCSndDYrBMCKCiiFpoSwwdZW0nJu/5JrO7220ttxDgN5lQ==
  template:
    metadata:
      name: livesync-couchdb-secret
      namespace: livesync
