---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: livesync-couchdb-secret
  namespace: livesync
spec:
  encryptedData:
    password: AgCBIa6KF6tZpYOa1VejgrYdQGBWk3Xr2MpuoWwvr1auiuUzk//mGYM1ykei8mPVGX45W/NKjMz24YaDYO5vDjGyC+q3BTvrnK/kVZ3+FSlalIpXVO2BqMnPC5WUQljpGCbSKU39wU73EBiGI2Ispi1HC7Czkyf76RtBS5ALX5DsuicFZxargPmeQ9Ao2dRoLMuxULhqOXNwxpGaIuH+IWjH5tbQcHcpYxNALf6YBpFS09UFKWWvUaM9AG+lf9ZxMI1hfrpdsDXNIpksT/hr4h+J8skY7Hi4B3by5KBS+FFBI+NPyoSfn7rpU+K7zuDGISeH5SaDqFBHrOvyHLbmStgM0qFWnf3ZDdBE3IBx2wZ23OBmUQRvIM/BjUe5wo3VjOLzh6SJPtmSTFVxiE/Q1QYLzKXjbCppuAOnuoCqxV8GA1Yh8upgFuQXjnAifVgDb+vftIlRRkdqPOP48ZqyidsXJNOY/pdnWHeXZUcCbjIylwlwgXVg6/wRKA1GtTh4XAyPk+1YunJL8VUIBCOrxSAInl5vZjp6m6+XSiOVQgTsYlZjh0Rl79JDb5pVqsyWjYIHPi9Lx4dWffRCIviWkZ3RHTsIEWwTkur/n51As1XI5SYWH0HBs41kI4q4Y5vl7S4RqDvUKS0fDBojgH0ar18n5Wn5zbNMEJbGETXVuDwri69zUP+vZ3w+avHr21mjs/VMlWthYIjh1a2maJvMvLWcaE1InTiY0+zmkx0TlkBrd5AuoykEVPWvgkfpVxDNfkmwTPt5a6ccPw==
  template:
    metadata:
      name: livesync-couchdb-secret
      namespace: livesync
