apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: glitchtip-ingress
  namespace: glitchtip
  annotations:
    th3borg.org/apps-healthcheck: "/api/0/"
    th3borg.org/apps-category: "infra"
    th3borg.org/apps-tier: "core"
    nginx.org/client-max-body-size: "50m"
spec:
  ingressClassName: nginx
  rules:
    - host: glitchtip.th3borg.org
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: glitchtip-web
                port:
                  number: 8000
