apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: glitchtip-uploads-pvc
  namespace: glitchtip
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 5Gi
