apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: glitchtip
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/FreyaAX400/TH3BORG.git
    targetRevision: HEAD
    path: apps/glitchtip
  destination:
    server: https://kubernetes.default.svc
    namespace: glitchtip
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
