apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: glitchtip
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://gitlab.com/api/v4/projects/16325141/packages/helm/stable
    chart: glitchtip
    targetRevision: "7.0.0"
    helm:
      releaseName: glitchtip
      values: |
        secret:
          SECRET_KEY: "Atw9l9ILoxTv6+1a1sdn9MHOzPBF1eGY5tOCOwNijeVODt3K7tUrF6/kskB1v5tJ
00U="
        existingSecret: "glitchtip-env"
        migrationJob:
          database:
            existingSecret: "glitchtip-env"
        web:
          replicaCount: 1
          database:
            existingSecret: "glitchtip-env"
          nodeSelector:
            kubernetes.io/hostname: borgling-1
          tolerations:
            - key: node-role.kubernetes.io/control-plane
              operator: Exists
              effect: NoSchedule
        worker:
          database:
            existingSecret: "glitchtip-env"
          nodeSelector:
            kubernetes.io/hostname: borgling-1
          tolerations:
            - key: node-role.kubernetes.io/control-plane
              operator: Exists
              effect: NoSchedule
        beat:
          nodeSelector:
            kubernetes.io/hostname: borgling-1
          tolerations:
            - key: node-role.kubernetes.io/control-plane
              operator: Exists
              effect: NoSchedule
        postgresql:
          primary:
            nodeSelector:
              kubernetes.io/hostname: borgling-1
            tolerations:
              - key: node-role.kubernetes.io/control-plane
                operator: Exists
                effect: NoSchedule
            persistence:
              size: 10Gi
              storageClass: local-path
        valkey:
          primary:
            nodeSelector:
              kubernetes.io/hostname: borgling-1
            tolerations:
              - key: node-role.kubernetes.io/control-plane
                operator: Exists
                effect: NoSchedule
        ingress:
          enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: glitchtip
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
