apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: "84.3.0"
    helm:
      releaseName: kube-prometheus-stack
      values: |
        grafana:
          enabled: true
          image:
            tag: "12.4.0"
          adminPassword: "changeme"
          ingress:
            enabled: true
            ingressClassName: nginx
            hosts:
              - grafana.th3borg.org
            path: /
            pathType: Prefix
          grafana.ini:
            server:
              root_url: "https://grafana.th3borg.org"
              serve_from_sub_path: false
          persistence:
            enabled: true
            size: 10Gi
            storageClassName: local-path
        prometheus:
          prometheusSpec:
            routePrefix: /prometheus
            externalUrl: "https://prometheus.th3borg.org"
            storageSpec:
              volumeClaimTemplate:
                spec:
                  storageClassName: local-path
                  accessModes: ["ReadWriteOnce"]
                  resources:
                    requests:
                      storage: 10Gi
          ingress:
            enabled: true
            ingressClassName: nginx
            hosts:
              - prometheus.th3borg.org
            paths:
              - /prometheus
            pathType: Prefix
        alertmanager:
          enabled: false
        nodeExporter:
          enabled: true
        kubeStateMetrics:
          enabled: true
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
