apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: livesync
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/JohanLarsson-Hall/TH3BORG.git
    targetRevision: HEAD
    path: apps/livesync
  destination:
    server: https://kubernetes.default.svc
    namespace: livesync
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
