apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: invidious-companion-cache
  namespace: invidious
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 5Gi
