---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: kavita-smb-secret
  namespace: kavita
spec:
  encryptedData:
    SMB_PASSWORD: AgAZRM8ssv8xTQ4skyiDdQYGp0R/f7ipebBep+Zk7PgnbEZIDpER6Zjcn+fbN/OK8oRUWTPRDH80GqHOuzdfNRuh/exsuD10dnBMVH+MKVESZx+wn/K3FRAJ2b/NR7tTZRJZVDjFpG6lr0jfd0Y0Y0R5gXSZQtP0ctI0qUJKf+OLJ0pOs6tLvMV561ibZEe1yiL0leIVnHOsR/ddbrWduXMDZ26YNXM3V0vnYQ3ng77PnBNzqEWPpf5rAs8gJTDD++u+tG20DAe5k/XLOc7i9BRUsIYLLja64YE1OJd5eG+gAzEXmu1yCOBqKZbtvI6CUUx7AcG+fXZd39HhZ2o9HsDteUTOpQkgnrzIF1ioG3plS/1ULmPm2tobUlqConMr7/jxdRFrxPZvmyjJK/zYdHmxfOzeKJx3DiwfWMRubIM/kT+pFo7GgkQ+6ZTgno7Kg24mrbz0w1w9waM/KrHu6yMJCT/+6fE3A1KTa0TQWL/bg5Uxnt3qy4lK04VTF99ehnx4d7pDZdhV5kweDS44LqjQRM9h9zD+dj5CRakNspVVf48DtJVJ46FUQLP1AV98nvslyiTK/2U1w28VSpJ8iA26zvr5EUgrOVf508AX2z0zj9Eim7e5MaaGm+5z2oemJeHycp+kj6bv9FhS5Ql4/GxRzeueoHb8xJ6eUGQGZix8hZ+bQLxZxvcQRtgUg1W0B102Y/XADqvAAOtFHAvPLPofNK6GDPScur/2ilHeOjE3peZtNOIEWOiInpOLWA==
  template:
    metadata:
      name: kavita-smb-secret
      namespace: kavita
