apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      serviceAccountName: api
      nodeSelector:
        kubernetes.io/hostname: borgling-1
      tolerations:
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
          effect: NoSchedule
      containers:
        - name: api
          image: 100.124.41.14:32000/th3borg-api:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          env:
            - name: PROMETHEUS_URL
              value: "http://kube-prometheus-stack-prometheus.monitoring:9090/prometheus"
            - name: GLITCHTIP_URL
              value: "http://glitchtip-web.glitchtip:8000"
            - name: GLITCHTIP_TOKEN
              valueFrom:
                secretKeyRef:
                  name: api-secrets
                  key: GLITCHTIP_TOKEN
            - name: API_KEYS
              valueFrom:
                secretKeyRef:
                  name: api-secrets
                  key: API_KEYS
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 30
