---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: gitea-db-secret
  namespace: gitea
spec:
  encryptedData:
    password: AgBtVOq/KmEi+FIiRQpHTER7dqHl8K6uTgkxeLs9PcxVJH3hgV1RmuNLxUMlMb5FITRPrXRZo+3USfOSQKVWHK27t50/MkHj6Gs/TDq7jbYKHx4vGxIYvkbHPCl71COtjBwTh5koN31/WYo7TG/WO83E2F4ajpSH90w/3nM0UQeMqviaN8rOp/b7MvkjcyJALzHfKG/JhN+Se/JTVzBkZrri7wkXSCVsIuk9VgXICpyI+VNk1vqP8WAcQFbkPfXV4Hqe+H7csgArN5b0rUJQR65u0dkWnsFB6jGS4W6xelnxKO9AVLe5MhYSK46BaggNXcDuYqvztla9thg/+7s/7R41aVEzBOjZGshUlE2rTr4ly3H1cB3oQI+qiPjatYWtunR7nO53mOirqVCFU74ypFRsBce+V9tCV/adIgsXT/NOrMMsx/DZPYMvJyHglTPIE/cqzEG6NuYs1YFEAOOuQV0YssZ4z7/gnEjpQbhnoj8dSJMBUjzteR1fo4miWaELSJxd7lxUsmj+TVbzkwZL74+qrklK+daSvif8hEzekHM9PNYDhOQFeIt0Igo6eT2GeGVQM96cV/XvNgmsSU2Iqej3OdZsYMOND8OwHckWVMZ5CT14bUiHWh5HFgCzF8ojUeVL/RFavVnOa2Y5T5+4yviM4pKI+iyRlkLK3SiQUyyenm9GL1L3sgz3Z+wRoamllUeN1xtFitsJe0zmS2yyXfbKUIezRNPawwcTz3Ov2VVYJPQOQEuW58u/gA==
    username: AgAJpUVcWxIuvJ8F3q5X8Ghp10/zqI+ZutvEZknHtEfV3rx8NHN8Y3M1pH29Qn+uZeShcFh1Sv7eR30WkRdr6GWyb7uWmTNP+3OiRJ89vY0qd8KBXMtm5w3oPmBIzjyUakiTvyeZB8aSCBpXSVuErM+ylCoI21aIDOgdJiB1ZH1vPiknDuzFCfLH9i6jFXOre5Y0/sBtRnE3/A6ycxglK3KI7I85AG3O1w3vp4CbSihLWhFVmA4fEtv4dnDeAWjV3KaYaXXWI30Brw2c1/T1iznOden/rxJM89mGWVb9UetRHx9Sa7DnYs3cOU/l7vO1wvYjrum1ynhmu8l592lcDJo70MHPRSlcg4YpQwbCXfvVcMIGBbxHjCzAKGpHWIuzK+nU4WjTC0Aw6DIxdXMyKO5QWHas9BVUIdfnRuTUqv/0oM3ZRn2YbHtjztiDpPpk8D9cHJaFzgMJPKvaK22mQownx6VthCufA7bOoydtPVOuKyqM07fZkBE6VxUcNSS/tIhii9tqV8RW9iGe/Iq8mhwrpo4qCaNzoYky4GTG/sGkboo4323p8ySdidOJSHvQrZFQFkprcoSMd1W+pZkalKLL8kjIXty/V8acRmUaf/biuPSVkIfLlSVnUerNrWy9ssXsGIqANCjRKcCaWnuwZxEvxoDgFqGun/BwOwJ7VzrypLkeEAGXS4pfcDcaU1WmJoU0sfCldQ==
  template:
    metadata:
      name: gitea-db-secret
      namespace: gitea
