---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argocd-secret
  namespace: argocd
spec:
  encryptedData:
    webhook.github.secret: AgCa1pn0AZ5IkfTapcCwX1oBN4SxRX2E5Hfu8vchJlRUn/090UwwCm+q4AuLXRy6u5KeU2FdLYUF/YtSbTUw0G1wPEDt5fPCtSrB4Hnok1Edk8nM9d9opLjbNzUdDHnkSjj04QSH6VTQzhwCPsMLz7WYRNF73Xd0XtXfl9v5MdCmcdTpYrgZhe6pMtsHw0m2iY8h9+XBjhdlJA6lx4LizhsH7keSK7sLY9Hdp6mHz+tEJw0Vwg+FO14KcMmh57o2EP5b3wohMcFemgL9NttLhRKGw/yYsr+V3b2t5dMjafY2YmVNyN4nRNoxqNoZXq/lEzsXgoxm58FyplA5fFbUkqjpI6IxlRDm4NVVTjwI1bQuW6OxMIyw16Pk2TyBTM+JuhK3b0Tfp1BeD44AzpsGBpf3AVN6Ut2HftMFaxq1wNMrj2Y6IgzfCrEZT1VJR2qYugk5k/ZwZr23tRWKGgYb6Qo95JrwJlNqoEinIK3cvxUruyz3UMPAsZnn1iw/R4mVDSkQy8eFhOwhpsJs4337MjGbyucYpw89GICXqUo1y724mNkHZ7cMqywFjajeol5HIN1NqDmZ5WInO5JJdmUnpnVOjR5hvVFpZyrzR2+5OUFtyYOG1JkvNjSPoeC6coL3VqTOcX3MsWzLA4OKnpZq0Tt5ohkircOuCLNWDQqMKO9/5MWRK4n2K4EISsnJIKqPUwgrYWujn7znDo27svO7k6Ntxu8VfI18Iz0aRJAeBKv2dxHvYBrPrmHDi9FirQ==
  template:
    metadata:
      name: argocd-secret
      namespace: argocd
