apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argocd-ingress
  namespace: argocd
  annotations:
    th3borg.org/apps-healthcheck: "/healthz"
    th3borg.org/apps-category: "infra"
    th3borg.org/apps-tier: "core"
spec:
  ingressClassName: nginx
  rules:
    - host: argocd.th3borg.org
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: argocd-server
                port:
                  number: 80
