---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: sentry-sentry-secret
  namespace: sentry
spec:
  encryptedData:
    key: AgA3pZgwzkFVUNx7Nzu475fuvIB6p0mlEj99rVsVFWauxmunIzlZ+atxxEBWQ46KMru4xVCaO635pQ6QyrnZ/wL+OKCOdbn40DmuHfMfVfoRqPG4Tmguh/koQ4y+mjNhMyKbbms5HXx6vFJbKAK/iCd0jRhtTbFgO+DwYFi/dpN6Bs5qjCr9CTw9FOKpqn9rwVh29k9kl5AUdu/ufQFF3PWcF02eR4Btwy90X6RutAOBzMktqEIk8c7UQS64Lg9NqUMcXmpvB793J58KLhBg5O1R2MytwQLO43alULvuYbmVY73JWl/67sto40kpFU5weEkit7XIAjSmNJFXBgAyS8S5f1PmUBvjduSRz2VZAhPkZVEZYNOxZg10F63KMC07iVur5M+t2eZxReMQ7Rqaqo2asEoGDShWAVZCy1du40GW/u1SFGoQmTcFmb81pX42O/wUp3JpeEbhm2DsojltX54Mz7US8pPrYju8VJEPgD1uVB/XuzPEPnHjVMbNXevjh593TkYfIjdXXf3T630WYT4qhl5bbHkkYxTcqDykj46ULmYHqpA2bDQuZa3zO2lPTq2U6C2jPwJi3budBgJPMOiDVvANME1fzc5ezf6P/xWfnkEYXYERmZtMJ+EtcnuJ0ARL6AnYN8yB59BI4aCetovqSfYRuJxIh7iPROrwvASL47AaL4ERFF/moLRVPCOzg+fLtBD8O2AEO7kdS6S8S9cC/Ce0pPINP6PSX+3VJweR/LydaU62O8VHwjPmy24M4NpRhLgLEPgobPKWm31UjguGqVMHjy4=
    user-password: AgCKjk73Bl7DZphkbQT1ux1pVb0w3Wy1AmLxjWgIL1kJrFWjtknHkWX1Z/PLH6Mgw3YLkrgFAjgBQFAz42BfSamVM1Dpk6nUlyvQ1l9E0FFzfB1XZNSUJ5KkRKJHoSsD/sRsve9hQWbHr6Lq2n6Z45UTLRm+Ix23S4sIJhmc7LZo6TkdSINWxmk9vHrPdLCa9T2Qi8P50EZJhDMP2owB7Nx0gLX8m+bvYMzu6W2Qqko9iWfJ8wy3Omv0L+7A/F28gQ4QGmEE8Nwcn+5owdEgPH4AZ+qQS5ixrBiDSc9E3TWJVOmPD9EzrjFPXWMvmoGNUVogUckUQWralDnQ0N44Y4OWUGWDs09Rqrl/3ZpH1Q9YcX+MqHS9SliQt+MxybXvRXbjG5HT1lg12ZpTvGwO0b+TxT8PvRA0waHzgjMEKTRZ4R6tU4Dct6RVGWClLFJHBZ6PyaymI+JntPUvyBASE9+nLYL0SYJ1bezpUy9qnf3LwavATyzM+YwkvU4hCvpBSgNk4foA93lGnhuXgxcbaf3Bi8jh6IYfKKA36Hz9aMSnBu5UdXSn4c/cVRWufRypsksffXPrzOOSAze98PQuzmGJ/1auheDNObk8mHDFTll6T+/uR5DbZBeoCLqRj7l+yVPIGkTI7mfwd4+Bs9K+p33SzSvUqk3U2ruYPl0OC9yLBvRBp1uW9KCoAt91h/C+Lywu39SIp2rBMQ==
  template:
    metadata:
      name: sentry-sentry-secret
      namespace: sentry
