apiVersion: v1
kind: Service
metadata:
  name: sentry-web-nodeport
  namespace: sentry
spec:
  type: NodePort
  selector:
    app: sentry
    component: web
  ports:
    - port: 9000
      targetPort: 9000
      nodePort: 31946
